<?php
namespace thedeveloperdad;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-24 at 15:34:47.
 */
class DollarTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Dollar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers thedeveloperdad\Dollar::times
     */
    public function testTimes()
    {
        $five = Money::dollar(5);
        
        // now we can compare Dollars to Dollars and remove the instance vars
        $this->assertEquals(new Money(10, "USD"), $five->times(2));   
        $this->assertEquals(new Money(15, "USD"), $five->times(3));
        
     
    }
    
    /**
     * @covers thedeveloperdad\Dollar::equals
     */
    public function testEquality()
    {
       $this->assertTrue(Money::dollar(5)->equals(Money::dollar(5)));
       $this->assertFalse(Money::dollar(5)->equals(Money::dollar(6)));
       
    }
    
    /**
     * @covers thedeveloperdad\Dollar::currency
     * @todo Implement currency
     */
    public function testCurrency()
    {
        $this->assertEquals("USD", Money::dollar(1)->currency());
        $this->assertEquals("CHF", Money::franc(1)->currency());
        
    }
    
  
   
   
}
