<?php

namespace thedeveloperdad;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-31 at 01:43:34.
 */
class PairTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Pair
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers thedeveloperdad\Pair::equals
     * @todo   Implement testEquals().
     */
    public function testEquals() {
        // Remove the following lines when you implement this test.
       $bank = new Bank();
       
       $bank->addRate("CHF", "USD", 4);
       //$bank->addRate("USD", "CHF", 6);
       $bank->addRate("YEN", "USD", 11);
       
       $rate = $bank->rate("CHF", "USD");
       echo $rate;
       
       //$this->assertTrue($bank->rate("USD", "CHF") == 4);
       
    }

    /**
     * @covers thedeveloperdad\Pair::hashCode
     * @todo   Implement testHashCode().
     */
    public function testHashCode() {
        // Remove the following lines when you implement this test.
        $pair = new Pair("boo", "bat");
         
        $this->assertTrue($pair->hashCode() == 0);
    }

}
